// This file was automatically generated by build.rs script.
// It can be used in examples with include! macro:
//     include!(concat!(env!("OUT_DIR"), "/examples_generated.rs"));
//
// Check examples/README.md file how to use environment variables to modify the file

#[allow(dead_code)]
use latticefold::decomposition_parameters::DecompositionParams;

#[derive(Clone)]
pub struct GoldilocksExampleDP {}

impl DecompositionParams for GoldilocksExampleDP {
    const B: u128 = 1 << 15; // Default: 1 << 15
    const L: usize = 5; // Default: 5
    const B_SMALL: usize = 2; // Default = 2
    const K: usize = 15; // Default = 15
}

#[derive(Clone)]
pub struct StarkPrimeExampleDP {}

impl DecompositionParams for StarkPrimeExampleDP {
    const B: u128 = 1073741824u128; // Default: 1073741824u128
    const L: usize = 9; // Default: 9
    const B_SMALL: usize = 2; // Default = 2
    const K: usize = 30; // Default = 30
}

#[derive(Clone)]
pub struct BabyBearExampleDP {}

impl DecompositionParams for BabyBearExampleDP {
    const B: u128 = 1 << 15; // Default: 1 << 15
    const L: usize = 5; // Default: 5
    const B_SMALL: usize = 2; // Default = 2
    const K: usize = 15; // Default = 15
}

#[derive(Clone)]
pub struct FrogExampleDP {}

impl DecompositionParams for FrogExampleDP {
    const B: u128 = 1 << 15; // Default: 1 << 15
    const L: usize = 5; // Default: 5
    const B_SMALL: usize = 2; // Default = 2
    const K: usize = 15; // Default = 15
}

const X_LEN: usize = 1; // Default = 1
const C: usize = 4; // Default = 4
const WIT_LEN: usize = 4; // Default = 4

const W_GOLDILOCKS: usize = WIT_LEN * GoldilocksExampleDP::L;
const W_BABYBEAR: usize = WIT_LEN * BabyBearExampleDP::L;
const W_FROG: usize = WIT_LEN * FrogExampleDP::L;

const X_LEN_STARK: usize = 1; // Default = 1
const C_STARK: usize = 15; // Default = 4
const WIT_LEN_STARK: usize = 30; // Default = 4

const W_STARK: usize = WIT_LEN_STARK * StarkPrimeExampleDP::L;
